
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantproject;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author Jalyway
 */
public class RestInfo extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public RestInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lab1 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        lab5 = new javax.swing.JLabel();
        lab6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("回首頁");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jLabel7.setFont(new java.awt.Font("新細明體", 1, 36)); // NOI18N
        jLabel7.setText("請選擇欲查詢餐廳");
        jPanel2.add(jLabel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        lab1.setIcon(new javax.swing.ImageIcon("D:\\Download\\Test\\DimSumLine.jpg")); // NOI18N
        lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab1MouseClicked(evt);
            }
        });
        jPanel1.add(lab1);

        lab2.setIcon(new javax.swing.ImageIcon("D:\\Download\\Test\\SUSHI.jpg")); // NOI18N
        lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab2MouseClicked(evt);
            }
        });
        jPanel1.add(lab2);

        lab3.setIcon(new javax.swing.ImageIcon("D:\\Download\\Test\\RockTwo.jpg")); // NOI18N
        lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab3MouseClicked(evt);
            }
        });
        jPanel1.add(lab3);

        lab4.setIcon(new javax.swing.ImageIcon("D:\\Download\\Test\\FuShoamTin.jpg")); // NOI18N
        lab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab4MouseClicked(evt);
            }
        });
        jPanel1.add(lab4);

        lab5.setIcon(new javax.swing.ImageIcon("D:\\Download\\Test\\SanShan.jpg")); // NOI18N
        lab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab5MouseClicked(evt);
            }
        });
        jPanel1.add(lab5);

        lab6.setIcon(new javax.swing.ImageIcon("D:\\Download\\Test\\Yoshinoya.jpg")); // NOI18N
        lab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab6MouseClicked(evt);
            }
        });
        jPanel1.add(lab6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseClicked
        // TODO add your handling code here:
        Chanege("https://www.google.com.tw/maps/place/%E7%82%B9%E5%BF%83%E9%81%93-%E6%9E%97%E6%A3%AE%E5%BA%97/@25.0547282,121.5238124,18.79z/data=!4m8!1m2!2m1!1z6bue5b-D5Yiw!3m4!1s0x0:0x16abf1c6db0497c4!8m2!3d25.0547841!4d121.525283");
    }//GEN-LAST:event_lab1MouseClicked

    private void lab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseClicked
        // TODO add your handling code here:
        Chanege("https://www.google.com.tw/maps/place/%E7%88%AD%E9%AE%AE%E8%BF%B4%E8%BD%89%E5%A3%BD%E5%8F%B8%EF%BC%88%E5%86%85%E5%A3%A2%E5%AE%B6%E6%A8%82%E7%A6%8F%EF%BC%89/@24.9723483,121.2525929,18.46z/data=!4m8!1m2!2m1!1z54it6a6u!3m4!1s0x34682206972b1bd3:0xc3f6b8371998c4e0!8m2!3d24.9724523!4d121.2536602");
    }//GEN-LAST:event_lab2MouseClicked

    private void lab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseClicked
        // TODO add your handling code here:
        Chanege("https://www.google.com.tw/maps/place/%E7%9F%B3%E4%BA%8C%E9%8D%8B+%E4%B8%AD%E5%A3%A2%E5%AE%B6%E6%A8%82%E7%A6%8F%E4%B8%AD%E5%B1%B1%E6%9D%B1%E5%BA%97/@24.9476167,121.2423937,17.58z/data=!4m8!1m2!2m1!1z55-z5LqM6Y2L!3m4!1s0x34682269582f7373:0x1848d6399000089a!8m2!3d24.9469487!4d121.2447202");
    }//GEN-LAST:event_lab3MouseClicked

    private void lab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab4MouseClicked
        // TODO add your handling code here:
        Chanege("https://www.google.com.tw/maps/place/%E7%A6%8F%E5%8B%9D%E4%BA%AD/@24.9734909,121.247119,16.42z/data=!4m8!1m2!2m1!1z56aP6IGW5Lqt!3m4!1s0x346821f8791fe543:0x3435050d36e87a2d!8m2!3d24.9735497!4d121.2527326");
    }//GEN-LAST:event_lab4MouseClicked

    private void lab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab5MouseClicked
        // TODO add your handling code here:
        Chanege("https://www.google.com.tw/maps/place/%E4%B8%89%E5%95%86%E5%B7%A7%E7%A6%8F/@24.9735994,121.2507827,18.25z/data=!4m8!1m2!2m1!1z5LiJ5ZWG5ben56aP!3m4!1s0x346821f8791fe543:0xb24f8ffdcb645d30!8m2!3d24.9735183!4d121.2526136");
    }//GEN-LAST:event_lab5MouseClicked

    private void lab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab6MouseClicked
        // TODO add your handling code here:
        Chanege("https://www.google.com.tw/maps/place/%E5%90%89%E9%87%8E%E5%AE%B6%E4%B8%AD%E5%A3%A2%E4%B8%AD%E6%AD%A3%E5%BA%97/@24.9540305,121.2244444,19.46z/data=!4m8!1m2!2m1!1z5ZCJ6YeO5a62!3m4!1s0x34682249079f0edf:0x1616b8f8e05374b1!8m2!3d24.9541979!4d121.2248383");
    }//GEN-LAST:event_lab6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home home=new Home();
        home.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestInfo().setVisible(true);
            }
        });
    }
    
    public void Chanege(String url){
        JFrame fr = new RestaurantDetail(url);
        fr.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        fr.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab5;
    private javax.swing.JLabel lab6;
    // End of variables declaration//GEN-END:variables
}
